In [17]:
from pandas_datareader import data as pdr
import pandas as pd
import yfinance as yf
yf.pdr_override()
import matplotlib.pyplot as plt

class Portfoliomaker:
  
    def get_tickers(tickers, date_from):
        x = pdr.get_data_yahoo(tickers, start=start_date)
        df = pd.DataFrame(x[['Adj Close', 'High', 'Low']])
        df.fillna(method='bfill', inplace=True)
        df.fillna(method='ffill', inplace=True)
        return df

In [18]:
tickers = ['BTC-USD', 'TLT', 'SPY']
df = get_tickers(tickers, '2018-01-04')
df

[*********************100%***********************]  3 of 3 completed

               Adj Close                                  High              \
                 BTC-USD         SPY         TLT       BTC-USD         SPY
Date
2018-01-03  15201.000000  254.885162  117.564018  15572.799805  270.640015
2018-01-04  15599.200195  255.959488  117.545380  15739.700195  272.160004
2018-01-05  17429.500000  257.665283  117.209724  17705.199219  273.559998
2018-01-06  17527.000000  258.136414  117.135117  17712.400391  274.100006
2018-01-07  16477.599609  258.136414  117.135117  17579.599609  274.100006
...                  ...         ...         ...           ...         ...
2021-05-27  38436.968750  419.290009  138.660004  40379.617188  420.720001
2021-05-28  35697.605469  420.040009  138.440002  38856.968750  421.250000
2021-05-29  34616.066406  420.040009  138.440002  37234.500000  421.250000
2021-05-30  35678.128906  420.040009  138.440002  36400.667969  421.250000
2021-05-31  36473.203125  420.040009  138.440002  37176.070312  421.250000

                                 Low
                   TLT       BTC-USD         SPY         TLT
Date
2018-01-03  126.199997  14844.500000  268.959991  125.489998
2018-01-04  126.160004  14522.200195  270.540009  125.370003
2018-01-05  126.180000  15202.799805  271.950012  125.360001
2018-01-06  126.029999  16764.599609  272.980011  125.169998
2018-01-07  126.029999  16087.700195  272.980011  125.169998
...                ...           ...         ...         ...
2021-05-27  138.690002  37247.902344  418.989990  137.990005
2021-05-28  139.300003  34779.039062  419.790009  138.339996
2021-05-29  139.300003  33693.929688  419.790009  138.339996
2021-05-30  139.300003  33520.738281  419.790009  138.339996
2021-05-31  139.300003  34249.679688  419.790009  138.339996

[1245 rows x 9 columns]